### ISSUE TITLE
u-boot-chip fails to build with oe/poky master

### ISSUE THREAD

**Issue by fmeerkoetter** [agherzan/meta-chip#7]
`ERROR: u-boot-chip-2015.07+gitAUTOINC+854d5fcc64-r0 do_compile: oe_runmake failed
ERROR: u-boot-chip-2015.07+gitAUTOINC+854d5fcc64-r0 do_compile: Function failed: do_compile (log file is located at /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/temp/log.do_compile.11909)
ERROR: Logfile of failure stored in: /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/temp/log.do_compile.11909
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8 CROSS_COMPILE=arm-oe-linux-gnueabi- CC=arm-oe-linux-gnueabi-gcc  --sysroot=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/chip V=1 HOSTCC=gcc  -isystem/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/include -O2 -pipe -L/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib -L/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/lib -Wl,-rpath-link,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib -Wl,-rpath-link,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/lib -Wl,-rpath,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib -Wl,-rpath,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/lib -Wl,-O1 -C /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git O=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build CHIP_defconfig
| NOTE: make -j 8 CROSS_COMPILE=arm-oe-linux-gnueabi- CC=arm-oe-linux-gnueabi-gcc  --sysroot=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/chip V=1 HOSTCC=gcc  -isystem/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/include -O2 -pipe -L/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib -L/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/lib -Wl,-rpath-link,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib -Wl,-rpath-link,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/lib -Wl,-rpath,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib -Wl,-rpath,/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/lib -Wl,-O1 -C /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git O=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build all
| make: Entering directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git'
| make -C /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build KBUILD_SRC=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git \
| -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/Makefile CHIP_defconfig
| make[1]: Entering directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build'
| make -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.build obj=scripts/basic
| ln -fsn /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git source
| /bin/bash /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/mkmakefile \
|     /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git . 2015 07
|   GEN     ./Makefile
| rm -f .tmp_quiet_recordmcount
| make -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.build obj=scripts/kconfig CHIP_defconfig
| scripts/kconfig/conf --defconfig=arch/../configs/CHIP_defconfig Kconfig
| #
| # configuration written to .config
| #
| make[1]: Leaving directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build'
| make: Leaving directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git'
| make: Entering directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git'
| make -C /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build KBUILD_SRC=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git \
| -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/Makefile all
| make[1]: Entering directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build'
| make -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/Makefile silentoldconfig
| make -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.build obj=scripts/basic
| ln -fsn /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git source
| /bin/bash /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/mkmakefile \
|     /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git . 2015 07
| rm -f .tmp_quiet_recordmcount
|   GEN     ./Makefile
| make -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.build obj=scripts/kconfig silentoldconfig
| mkdir -p include/config include/generated
| scripts/kconfig/conf --silentoldconfig Kconfig
| make -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf || \
|       { rm -f include/config/auto.conf; false; }
| mkdir -p include/asm
| if [ -d /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/arch/arm/mach-sunxi/include/mach ]; then        \
|       dest=arch/arm/mach-sunxi/include/mach;                  \
| else                                                                  \
|       dest=arch/arm/include/asm/arch-sunxi;   \
| fi;                                                                   \
| ln -fsn /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/$dest include/asm/arch
| set -e; : '  CHK     include/config.h'; mkdir -p include/;    (echo "/* Automatically generated - do not edit */"; for i in $(echo "CONS_INDEX=2,AXP209_POWER,ENV_IS_IN_NAND" | sed 's/,/ /g'); do echo \#define CONFIG_$i | sed '/=/ {s/=/     /;q; } ; { s/$/ 1/; }'; done; echo \#define CONFIG_BOARDDIR board/sunxi; echo \#include \<config_defaults.h\>; echo \#include \<config_uncmd_spl.h\>; echo \#include \<configs/"sun5i".h\>; echo \#include \<asm/config.h\>; echo \#include \<config_fallbacks.h\>;) < /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf > include/config.h.tmp; if [ -r include/config.h ] && cmp -s include/config.h include/config.h.tmp; then rm -f include/config.h.tmp; else : '  UPD     include/config.h'; mv -f include/config.h.tmp include/config.h; fi
| mkdir -p spl/include/
|   arm-oe-linux-gnueabi-gcc  --sysroot=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/chip -E -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -O2 -fno-stack-protector -fno-delete-null-pointer-checks -g -fstack-usage -Wno-format-nonliteral -Werror=date-time  -D__KERNEL__ -D__UBOOT__   -D__ARM__ -marm -mno-thumb-interwork  -mabi=aapcs-linux  -mword-relocations  -mno-unaligned-access  -ffunction-sections -fdata-sections -fno-common -ffixed-r9  -pipe -Iinclude  -I/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include -I/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/arch/arm/include -include /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/kconfig.h  -nostdinc -isystem /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/6.2.0/include  -DDO_DEPS_ONLY -dM /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h > include/autoconf.mk.tmp && { sed -n -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/tools/scripts/define2mk.sed include/autoconf.mk.tmp | while read line; do if [ -n "" ] || ! grep -q "${line%=*}=" include/config/auto.conf; then echo "$line"; fi done > include/autoconf.mk; rm include/autoconf.mk.tmp; } || { rm include/autoconf.mk.tmp; false; }
|   arm-oe-linux-gnueabi-gcc  --sysroot=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/chip -x c -DDO_DEPS_ONLY -M -MP -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -O2 -fno-stack-protector -fno-delete-null-pointer-checks -g -fstack-usage -Wno-format-nonliteral -Werror=date-time  -D__KERNEL__ -D__UBOOT__   -D__ARM__ -marm -mno-thumb-interwork  -mabi=aapcs-linux  -mword-relocations  -mno-unaligned-access  -ffunction-sections -fdata-sections -fno-common -ffixed-r9  -pipe -Iinclude  -I/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include -I/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/arch/arm/include -include /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/kconfig.h  -nostdinc -isystem /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/6.2.0/include -MQ include/config/auto.conf /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h > include/autoconf.mk.dep || { rm include/autoconf.mk.dep; false; }
| ERROR: oe_runmake failed
|   arm-oe-linux-gnueabi-gcc  --sysroot=/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/chip -E -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -O2 -fno-stack-protector -fno-delete-null-pointer-checks -g -fstack-usage -Wno-format-nonliteral -Werror=date-time  -D__KERNEL__ -D__UBOOT__   -D__ARM__ -marm -mno-thumb-interwork  -mabi=aapcs-linux  -mword-relocations  -mno-unaligned-access  -ffunction-sections -fdata-sections -fno-common -ffixed-r9  -pipe -Iinclude  -I/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include -I/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/arch/arm/include -include /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/kconfig.h  -nostdinc -isystem /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/sysroots/x86_64-linux/usr/lib/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/6.2.0/include -DCONFIG_SPL_BUILD -DDO_DEPS_ONLY -dM /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h > spl/include/autoconf.mk.tmp && { sed -n -f /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/tools/scripts/define2mk.sed spl/include/autoconf.mk.tmp | while read line; do if [ -n "" ] || ! grep -q "${line%=*}=" include/config/auto.conf; then echo "$line"; fi done > spl/include/autoconf.mk; rm spl/include/autoconf.mk.tmp; } || { rm spl/include/autoconf.mk.tmp; false; }
| In file included from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler.h:54:0,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/part_efi.h:16,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/part.h:180,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h:80:
| /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
|  #include gcc_header(__GNUC__)
|                               ^
| In file included from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler.h:54:0,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/part_efi.h:16,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/part.h:180,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h:80:
| /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
|  #include gcc_header(__GNUC__)
|                               ^
| compilation terminated.
| compilation terminated.
| /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf:47: recipe for target 'include/autoconf.mk.dep' failed
| make[2]: *** [include/autoconf.mk.dep] Error 1
| make[2]: *** Waiting for unfinished jobs....
| /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf:72: recipe for target 'include/autoconf.mk' failed
| make[2]: *** [include/autoconf.mk] Error 1
| In file included from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler.h:54:0,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/byteorder/little_endian.h:12,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/arch/arm/include/asm/byteorder.h:29,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/compiler.h:125,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/image.h:19,
|                  from /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h:82:
| /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
|  #include gcc_header(__GNUC__)
|                               ^
| compilation terminated.
| /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf:75: recipe for target 'spl/include/autoconf.mk' failed
| make[2]: *** [spl/include/autoconf.mk] Error 1
| make[1]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/uboot.release'.  Stop.
| make[1]: Leaving directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build'
| Makefile:145: recipe for target 'sub-make' failed
| make: *** [sub-make] Error 2
| make: Leaving directory '/data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git'
| ERROR: Function failed: do_compile (log file is located at /data/projects/rpi-a2dp-sink/chip-build/tmp-glibc/work/chip-oe-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/temp/log.do_compile.11909)
ERROR: Task (/data/projects/rpi-a2dp-sink/meta-chip/recipes-bsp/u-boot/u-boot-chip_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 400 tasks of which 398 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /data/projects/rpi-a2dp-sink/meta-chip/recipes-bsp/u-boot/u-boot-chip_git.bb:do_compile`

**Comment by agherzan** [comment]
Fixed in master and pyro branches.
